### ISSUE TITLE
The Room entity should not contain messages, but indications to them.

### ISSUE THREAD

**Issue by MarcinMikolaj** [MarcinMikolaj/rtCommunicator#20]
- [x] Modify the Room entity. Should not contain message list but the identifier associated with the message.
- [x] Message entity should contain private key.
- [x] Update services for changes made to the entity.
- [x] Add possibility to generate unique key for message.
- [x] Make other necessary changes to make the application work properly as in the case of the previous version not based on keys.
