### ISSUE TITLE
Think about improving the app based on your ideas.

### ISSUE THREAD

**Issue by MarcinMikolaj** [MarcinMikolaj/rtCommunicator#60]
- [ ] Message queuing using Apache Kafka.
- [ ] Rewrite frontend application using React framework.
- [ ] Add Feature Flag for new features.
- [ ] Add monitoring using Prometheus and Grafana.
- [ ] Build your application based on micro services.

Before micro service based application you should have monitoring and feature flag.
